name: Release-plz

permissions:
  contents: write

on:
  workflow_dispatch: { }

jobs:
  # Release unpublished packages.
  release-plz-release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged }}
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Pre-release tests
        run: |-
          sudo apt-get install -y protobuf-compiler
          cargo install kopium
          cargo test
          cargo test --manifest-path=sdk/Cargo.toml --features k8s-openapi,k8s-openapi/v1_33
          cargo clippy
          cargo install --locked cargo-deny
          cargo deny check license
      - name: k3d integration test
        run: |-
          sudo wget -O /usr/bin/crossplane https://releases.crossplane.io/stable/current/bin/linux_amd64/crank
          sudo chmod +x /usr/bin/crossplane
          gh release download --repo k3d-io/k3d --pattern k3d-linux-amd64 --output k3d
          sudo mv k3d /usr/bin/k3d
          sudo chmod +x /usr/bin/k3d
          cd example/local_test
          ./run.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_CARGO_REGISTRY_TOKEN }}